FROM node:8.1.4-alpine
MAINTAINER b

# Prepare app directory
RUN mkdir /code
WORKDIR /code


ADD package.json /code/
RUN npm install

ADD . /code/

# Expose the app port
EXPOSE 8000

# Start the app
CMD [ "npm", "start" ]
